Mailing/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from Mailing.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clients/', include('client.client_urls', namespace='clients')),
    path('message/', include('client.message_urls', namespace='message')),
    path('', include('client.mail_urls', namespace='mail')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView, HomePageView

app_name = BlogConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='blog_home'),
    path('all/', BlogListView.as_view(), name='blog_list'),
    path('more/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, email_verification, UserListView, UserBanView, UserProfileView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registr/', RegisterView.as_view(), name='register'),
    path('confirm/<str:token>/', email_verification, name='email_verification'),
    path('all/', UserListView.as_view(), name='list_users'),
    path('ban/<int:pk>', UserBanView.as_view(), name='ban_user'),
    path('profile/<int:pk>', UserProfileView.as_view(), name='profile_user'),
]

client/models.py
from django.db import models

from users.models import User

NULLABLE = {
    'blank': True,
    'null': True,
}


class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name="email")
    full_name = models.CharField(max_length=70, verbose_name="full name", **NULLABLE)
    comment = models.CharField(max_length=300, verbose_name="comment", **NULLABLE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="owner")

    def __str__(self):
        return f"{self.email} {self.full_name}"


class Message(models.Model):
    topic = models.CharField(max_length=100, verbose_name="topic")
    message = models.TextField(verbose_name='message')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="owner")

    def __str__(self):
        return f"{self.topic}"


class Mail(models.Model):
    PERIODICITY_CHOICES = [
        ('day', 'Каждый день'),
        ('week', 'Каждую неделю'),
        ('month', 'Каждый месяц'),
    ]

    STATUS_CHOICES = [
        ('created', 'Создана'),
        ('started', 'Запущена'),
        ('failed', 'Ошибка'),
        ('completed', 'Завершена'),
    ]

    time_for_sending = models.DateTimeField(verbose_name="first mailing date")
    periodicity = models.CharField(max_length=20, choices=PERIODICITY_CHOICES, default='week',
                                   verbose_name="periodicity")
    recipients = models.ManyToManyField(Client, related_name='mails', verbose_name="recipients")
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name="message")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='created', verbose_name="status")
    is_active = models.BooleanField(default=True, verbose_name="is active")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='mails', verbose_name="owner")

    def __str__(self):
        return f"{self.pk}"


class Attempt(models.Model):
    last_modified_date = models.DateTimeField(auto_now=True, verbose_name="last modified date")
    mail_response = models.TextField(verbose_name="mail response", **NULLABLE)
    mail = models.ForeignKey(Mail, on_delete=models.CASCADE, related_name='attempt', verbose_name='mail')

    def __str__(self):
        return f"{self.pk}"

client/forms.py
from django import forms

from client.models import Client, Message, Mail


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        exclude = ['owner']
        widgets = {
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter email address'
            }),
            'full_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter full name'
            }),
            'comment': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Add a comment (optional)',
                'rows': 4
            }),
            'owner': forms.Select(attrs={
                'class': 'form-select'
            }),
        }


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        exclude = ['owner']
        widgets = {
            'topic': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the topic of the message'
            }),
            'message': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Write your message here...',
                'rows': 6
            }),
            'owner': forms.Select(attrs={
                'class': 'form-select'
            }),
        }


class MailForm(forms.ModelForm):
    class Meta:
        model = Mail
        exclude = ['status', 'is_active', 'owner']

        widgets = {
            'time_for_sending': forms.DateTimeInput(
                attrs={'type': 'datetime-local'},
                format='%Y-%m-%dT%H:%M'
            ),
            'recipients': forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if self.user:
            self.fields['recipients'].queryset = Client.objects.filter(owner=self.user)
            self.fields['message'].queryset = Message.objects.filter(owner=self.user)


class MailManagerForm(forms.ModelForm):
    class Meta:
        model = Mail
        fields = ['is_active']

client/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from client.forms import ClientForm, MessageForm, MailForm, MailManagerForm
from client.models import Client, Message, Mail


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    context_object_name = 'clients'
    login_url = reverse_lazy('users:login')

    def get_queryset(self):
        user = self.request.user

        if user.is_superuser or user.groups.filter(name='Managers').exists():
            return Client.objects.all()

        return Client.objects.filter(owner=user)


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client
    context_object_name = 'client'
    login_url = reverse_lazy('users:login')


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('clients:clients_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('clients:clients_list')


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('clients:clients_list')


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    context_object_name = 'messages'
    login_url = reverse_lazy('users:login')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        for message in context['messages']:
            message.message = message.message[:50]

        return context

    def get_queryset(self):
        user = self.request.user

        if user.is_superuser or user.groups.filter(name='Managers').exists():
            return Message.objects.all()

        return Message.objects.filter(owner=user)


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    context_object_name = 'messages'
    login_url = reverse_lazy('users:login')


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('message:message_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('message:message_list')


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('message:message_list')


class MailListView(LoginRequiredMixin, ListView):
    model = Mail
    context_object_name = 'mails'
    login_url = reverse_lazy('users:login')

    def get_queryset(self):
        user = self.request.user

        if user.is_superuser or user.groups.filter(name='Managers').exists():
            return Mail.objects.all()

        return Mail.objects.filter(owner=user)


class MailDetailView(LoginRequiredMixin, DetailView):
    model = Mail
    context_object_name = 'mails'
    login_url = reverse_lazy('users:login')


class MailCreateView(LoginRequiredMixin, CreateView):
    model = Mail
    form_class = MailForm
    success_url = reverse_lazy('mail:mail_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MailUpdateView(LoginRequiredMixin, UpdateView):
    model = Mail
    form_class = MailForm
    success_url = reverse_lazy('mail:mail_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_form_class(self):
        user = self.request.user

        if user == self.object.owner or user.is_superuser:
            return MailForm
        elif user.groups.filter(name='Managers').exists():
            return MailManagerForm
        return PermissionDenied


class MailDeleteView(LoginRequiredMixin, DeleteView):
    model = Mail
    success_url = reverse_lazy('mail:mail_list')

client/templates/client/base.html
{% load custom_tags %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mailing</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Mailing</h5>
    <nav class="me-auto ms-3">
        <a class="p-2 btn btn-outline-primary" href="{% url 'mail:mail_list' %}">Рассылки</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'clients:clients_list' %}">База клиентов</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'message:message_list' %}">База сообщений</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:blog_home' %}">Блог</a>
        {% if user.is_superuser or user|has_group:"Managers" %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:list_users' %}">База пользователей</a>
        {% endif %}
    </nav>

    <div class="ms-auto">
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile_user' user.pk %}">Профиль</a>
            <form method="post" action="{% url 'users:logout' %}" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="p-2 btn btn-outline-primary">Выйти</button>
            </form>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </div>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Mailing</h1>
</div>

<div class="container">

    {% block products %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Mailing
                <small class="d-block mb-3 text-muted">&copy; {% now "Y" %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'mail:mail_list' %}">Рассылки</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

client/templates/client/client_confirm_delete.html
{% extends 'client/base.html' %}


{% block products %}
    <div class="container mt-5">
        <h2 class="text-center mb-4">Подтвердите удаление</h2>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body text-center">
                        <p class="lead">Вы уверены, что хотите удалить клиента "<strong>{{ object.email }}</strong>"?</p>
                        <form method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Удалить</button>
                            <a href="{% url 'clients:clients_list' %}" class="btn btn-secondary">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/client_detail.html
{% extends 'client/base.html' %}


{% block products %}
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ client.email }}</h2>
                    <p class="card-text">Name: {{ client.full_name }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <p>Comment: {{ client.comment }}</p>
                            <a href="{% url 'clients:clients_update' client.pk %}"
                               class="btn btn-warning btn-sm">Обновить</a>
                            <a href="{% url 'clients:clients_delete' client.pk %}"
                               class="btn btn-danger btn-sm">Удалить</a>
                        </div>
                    </div>
                </div>
                <a href="{% url 'clients:clients_list' %}" class="btn btn-info btn-sm">Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/client_form.html
{% extends 'client/base.html' %}

{% block products %}
    <div class="row text-center">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                            Обновить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                    <a href="{% url 'clients:clients_list' %}" class="btn btn-secondary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/client_list.html
{% extends 'client/base.html' %}


{% block products %}
    <div class="row text-center">
        <div class="mb-4 text-end">
            <a href="{% url 'clients:clients_create' %}" class="btn btn-success">Добавить клиента</a>
        </div>
        {% for client in clients %}
            <div class="col-6">

                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ client.full_name }}</h4>
                        <h4 class="my-0 font-weight-normal">{{ client.email }}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{ client.comment }}</li>
                        </ul>
                        <div class="d-flex justify-content-between">
                            <a href="{% url 'clients:clients_update' client.pk %}" class="btn btn-info">
                                Изменить клиента
                            </a>
                            <a href="{% url 'clients:clients_delete' client.pk %}" class="btn btn-primary">
                                Удалить клиента
                            </a>
                            <a href="{% url 'clients:clients_more' client.pk %}" class="btn btn-primary">
                                Подробнее
                            </a>
                        </div>
                    </div>
                </div>

            </div>
        {% endfor %}
    </div>
{% endblock %}

client/templates/client/mail_confirm_delete.html
{% extends 'client/base.html' %}


{% block products %}
    <div class="container mt-5">
        <h2 class="text-center mb-4">Подтвердите удаление</h2>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body text-center">
                        <p class="lead">Вы уверены, что хотите удалить рассылку "<strong>{{ object.message.topic }}</strong>"?</p>
                        <form method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Удалить</button>
                            <a href="{% url 'clients:clients_list' %}" class="btn btn-secondary">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/mail_detail.html
{% extends 'client/base.html' %}


{% block products %}
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ mails.owner.email }}</h2>
                    <p class="card-text">Topic: {{ mails.message.topic }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <p>Next time for sending: {{ mails.time_for_sending }}</p>
                            <p>Periodicity: {{ mails.periodicity }}</p>
                            <p>Quantity clients: {{ mails.recipients.count }}</p>
                            <p>Status: {{ mails.status }}</p>
                            <p>Active: {{ mails.is_active }}</p>
                            <a href="{% url 'mail:mail_update' mails.pk %}"
                               class="btn btn-warning btn-sm">Обновить</a>
                            <a href="{% url 'mail:mail_delete' mails.pk %}"
                               class="btn btn-danger btn-sm">Удалить</a>
                        </div>
                    </div>
                </div>
                <a href="{% url 'mail:mail_list' %}" class="btn btn-info btn-sm">Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/mail_form.html
{% extends 'client/base.html' %}

{% block products %}
    <div class="row text-center">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                            Обновить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                    <a href="{% url 'mail:mail_list' %}" class="btn btn-secondary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/mail_list.html
{% extends 'client/base.html' %}


{% block products %}
    <div class="row text-center">
        <div class="mb-4 text-end">
            <a href="{% url 'mail:mail_create' %}" class="btn btn-success">Добавить рассылку</a>
        </div>
        {% for mail in mails %}
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ mail.message.topic }}</h4>
                        {% if user != mail.owner %}
                            <h5 class="my-0 font-weight-normal">{{ mail.owner.email }}</h5>
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>mailing will begin at: {{ mail.time_for_sending }}</li>
                            <li>every {{ mail.periodicity }}</li>
                            <li>status: {{ mail.status }}</li>
                            <li>sent: {{ mail.recipients.count }}</li>
                            <li>unsent: {{ mail.attempt.count }}</li>
                            <li>active: {{ mail.is_active }}</li>
                        </ul>
                        <div class="d-flex justify-content-between">
                            <a href="{% url 'mail:mail_update' mail.pk %}" class="btn btn-info">
                                Изменить рассылку
                            </a>
                            <a href="{% url 'mail:mail_delete' mail.pk %}" class="btn btn-primary">
                                Удалить рассылку
                            </a>
                            <a href="{% url 'mail:mail_more' mail.pk %}" class="btn btn-primary">
                                Подробнее
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

client/templates/client/message_confirm_delete.html
{% extends 'client/base.html' %}


{% block products %}
    <div class="container mt-5">
        <h2 class="text-center mb-4">Подтвердите удаление</h2>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body text-center">
                        <p class="lead">Вы уверены, что хотите удалить сообщение "<strong>{{ object.topic }}</strong>"?</p>
                        <form method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Удалить</button>
                            <a href="{% url 'message:message_list' %}" class="btn btn-secondary">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/message_detail.html
{% extends 'client/base.html' %}


{% block products %}
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ messages.topic }}</h2>
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <p>Message: {{ messages.message }}</p>
                            <a href="{% url 'message:message_update' messages.pk %}"
                               class="btn btn-warning btn-sm">Обновить</a>
                            <a href="{% url 'message:message_delete' messages.pk %}"
                               class="btn btn-danger btn-sm">Удалить</a>
                        </div>
                    </div>
                </div>
                <a href="{% url 'message:message_list' %}" class="btn btn-info btn-sm">Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/message_form.html
{% extends 'client/base.html' %}

{% block products %}
    <div class="row text-center">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                            Обновить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                    <a href="{% url 'message:message_list' %}" class="btn btn-secondary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/message_list.html
{% extends 'client/base.html' %}


{% block products %}
    <div class="row text-center">
        <div class="mb-4 text-end">
            <a href="{% url 'message:message_create' %}" class="btn btn-success">Добавить сообщение</a>
        </div>
        {% for message in messages %}
            <div class="col-6">

                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ message.topic }}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{ message.message }}</li>
                        </ul>
                        <div class="d-flex justify-content-between">
                            <a href="{% url 'message:message_update' message.pk %}" class="btn btn-info">
                                Изменить сообщение
                            </a>
                            <a href="{% url 'message:message_delete' message.pk %}" class="btn btn-primary">
                                Удалить сообщение
                            </a>
                            <a href="{% url 'message:message_more' message.pk %}" class="btn btn-primary">
                                Подробнее
                            </a>
                        </div>
                    </div>
                </div>

            </div>
        {% endfor %}
    </div>
{% endblock %}