Mailing/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from Mailing.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clients/', include('client.client_urls', namespace='clients')),
    path('message/', include('client.message_urls', namespace='message')),
    path('', include('client.mail_urls', namespace='mail')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView, HomePageView

app_name = BlogConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='blog_home'),
    path('all/', BlogListView.as_view(), name='blog_list'),
    path('more/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

blog/models.py
from django.db import models

NULLABLE = {"blank": True,
            "null": True}


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='title')
    content = models.TextField(verbose_name='content', **NULLABLE)
    img = models.ImageField(upload_to="images/", verbose_name="image", **NULLABLE)
    views = models.IntegerField(default=0, verbose_name="views")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="created at")
    is_active = models.BooleanField(default=True, verbose_name="active")

    def __str__(self):
        return f"{self.title}"

client/models.py
from django.db import models

from users.models import User

NULLABLE = {
    'blank': True,
    'null': True,
}


class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name="email")
    full_name = models.CharField(max_length=70, verbose_name="full name", **NULLABLE)
    comment = models.CharField(max_length=300, verbose_name="comment", **NULLABLE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="owner")

    def __str__(self):
        return f"{self.email} {self.full_name}"


class Message(models.Model):
    topic = models.CharField(max_length=100, verbose_name="topic")
    message = models.TextField(verbose_name='message')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="owner")

    def __str__(self):
        return f"{self.topic}"


class Mail(models.Model):
    PERIODICITY_CHOICES = [
        ('day', 'Каждый день'),
        ('week', 'Каждую неделю'),
        ('month', 'Каждый месяц'),
    ]

    STATUS_CHOICES = [
        ('created', 'Создана'),
        ('started', 'Запущена'),
        ('failed', 'Ошибка'),
        ('completed', 'Завершена'),
    ]

    time_for_sending = models.DateTimeField(verbose_name="first mailing date")
    periodicity = models.CharField(max_length=20, choices=PERIODICITY_CHOICES, default='week',
                                   verbose_name="periodicity")
    recipients = models.ManyToManyField(Client, related_name='mails', verbose_name="recipients")
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name="message")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='created', verbose_name="status")
    is_active = models.BooleanField(default=True, verbose_name="is active")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='mails', verbose_name="owner")

    def __str__(self):
        return f"{self.pk}"


class Attempt(models.Model):
    last_modified_date = models.DateTimeField(auto_now=True, verbose_name="last modified date")
    mail_response = models.TextField(verbose_name="mail response", **NULLABLE)
    mail = models.ForeignKey(Mail, on_delete=models.CASCADE, related_name='attempt', verbose_name='mail')

    def __str__(self):
        return f"{self.pk}"

blog/forms.py
from django import forms

from blog.models import Blog


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        exclude = ['views', 'created_at']

        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите заголовок'
            }),
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Введите содержание',
                'rows': 5
            }),
            'img': forms.ClearableFileInput(attrs={
                'class': 'form-control-file'
            }),
            'is_active': forms.CheckboxInput(attrs={
                'class': 'form-check-input'
            }),
        }

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, CreateView, ListView, UpdateView, DeleteView, TemplateView

from blog.forms import BlogForm
from blog.models import Blog
from blog.services import get_mails_from_cache, get_clients_from_cache


class BlogListView(ListView):
    model = Blog
    context_object_name = 'posts'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        for post in context['posts']:
            post.content = post.content[:25]
        return context

    def get_queryset(self):
        return Blog.objects.filter(is_active=True).order_by('-views')


class BlogDetailView(DetailView):
    model = Blog
    context_object_name = 'post'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')


class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogForm

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')


class HomePageView(TemplateView):
    template_name = 'blog/home_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        mails_list = get_mails_from_cache()
        clients_list = get_clients_from_cache()

        total_mailings = mails_list.count()
        active_mailings = mails_list.filter(is_active=True).count()
        unique_clients = clients_list.count()
        last_blogs = Blog.objects.filter(is_active=True).order_by("?")[:3]

        context['total_mailings'] = total_mailings
        context['active_mailings'] = active_mailings
        context['unique_clients'] = unique_clients
        context['last_blogs'] = last_blogs

        return context

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mailing Blog</title>
    <!-- Подключение Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<!-- Шапка сайта -->
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Mailing</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:blog_home' %}">Домой</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'mail:mail_list' %}">Рассылки</a>
    </nav>
</div>

<!-- Заголовок блога -->
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блог Mailing</h1>
</div>

<!-- Основной контент -->
<div class="container">


    <div class="mb-4 text-end">
        <a href="{% url 'blog:blog_create' %}" class="btn btn-success">Создать пост</a>
    </div>

    {% block post_card %}
    {% endblock %}

    <!-- Футер -->
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Mailing
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
        </div>
    </footer>

    <!-- Подключение Bootstrap JS и Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
</div>
</body>
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends 'blog/base.html' %}


{% block post_card %}
    <div class="container mt-5">
        <h2 class="text-center mb-4">Подтвердите удаление</h2>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body text-center">
                        <p class="lead">Вы уверены, что хотите удалить пост "<strong>{{ object.title }}</strong>"?</p>
                        <form method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Удалить</button>
                            <a href="{% url 'blog:blog_list' %}" class="btn btn-secondary">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}


{% block post_card %}
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    {% if post.img %}
                        <img src="{{ post.img.url }}" class="card-img-top"/>
                    {% else %}
                        <p>Изображение отсутствует</p>
                    {% endif %}
                    <p class="card-text">{{ post.content }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <p>Просмотры: {{ post.views }}</p>
                            <a href="{% url 'blog:blog_update' post.pk %}"
                               class="btn btn-warning btn-sm">Обновить</a>
                            <a href="{% url 'blog:blog_delete' post.pk %}" class="btn btn-danger btn-sm">Удалить</a>
                        </div>
                    </div>
                    <div class="card-footer text-muted">
                        Опубликовано: {{ post.created_at }}
                    </div>
                </div>
                <a href="{% url 'blog:blog_list' %}" class="btn btn-info btn-sm">Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/base.html' %}

{% block post_card %}
    <div class="container mt-5">
        <h2 class="text-center mb-4">Создать новый пост</h2>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                            Обновить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                    <a href="{% url 'blog:blog_list' %}" class="btn btn-secondary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% load my_tags %}


{% block post_card %}
    <div class="row">
        <div class="col-md-8 offset-md-2">
            {% for post in posts %}
                <div class="card mb-4">
                    <div class="card-body">
                        <h2 class="card-title">{{ post.title }}</h2>
                        {% if post.img %}
                            <img src="{{ post.img.url }}" class="card-img-top"/>
                        {% else %}
                            <p>Изображение отсутствует</p>
                        {% endif %}
                        <p class="card-text">{{ post.content }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div>
                                <a href="{% url 'blog:blog_update' post.pk %}"
                                   class="btn btn-warning btn-sm">Обновить</a>
                                <a href="{% url 'blog:blog_delete' post.pk %}" class="btn btn-danger btn-sm">Удалить</a>
                            </div>
                            <a href="{% url 'blog:blog_detail' post.pk %}" class="btn btn-primary btn-sm">Читать
                                далее</a>
                        </div>
                    </div>
                    <div class="card-footer text-muted">
                        Опубликовано: {{ post.created_at }}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    </div>
{% endblock %}

blog/templates/blog/home_page.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mailing Blog</title>
    <!-- Подключение Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<!-- Шапка сайта -->
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Mailing</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'mail:mail_list' %}">Рассылки</a>
    </nav>
</div>

<!-- Заголовок блога -->
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блог Mailing</h1>
</div>

<!-- Основной контент -->
<div class="container">

    <div class="row mb-4">
        <div class="col-md-4">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Всего рассылок</h5>
                    <p class="card-text">{{ total_mailings }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Активных рассылок</h5>
                    <p class="card-text">{{ active_mailings }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Уникальных клиентов</h5>
                    <p class="card-text">{{ unique_clients }}</p>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        {% for post in last_blogs %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <div class="card-body">
                        <h2 class="card-title">{{ post.title }}</h2>
                        {% if post.img %}
                            <img src="{{ post.img.url }}" class="card-img-top"/>
                        {% else %}
                            <p>Изображение отсутствует</p>
                        {% endif %}
                        <p class="card-text">{{ post.content }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div>
                                <a href="{% url 'blog:blog_update' post.pk %}"
                                   class="btn btn-warning btn-sm">Обновить</a>
                                <a href="{% url 'blog:blog_delete' post.pk %}" class="btn btn-danger btn-sm">Удалить</a>
                            </div>
                            <a href="{% url 'blog:blog_detail' post.pk %}" class="btn btn-primary btn-sm">Читать
                                далее</a>
                        </div>
                    </div>
                    <div class="card-footer text-muted">
                        Опубликовано: {{ post.created_at }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="mb-4 text-end">
        <a href="{% url 'blog:blog_list' %}" class="btn btn-success">Все посты</a>
    </div>

    <!-- Футер -->
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Mailing
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
        </div>
    </footer>

    <!-- Подключение Bootstrap JS и Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
</div>
</body>
</html>