Mailing/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from Mailing.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clients/', include('client.client_urls', namespace='clients')),
    path('message/', include('client.message_urls', namespace='message')),
    path('', include('client.mail_urls', namespace='mail')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView, HomePageView

app_name = BlogConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='blog_home'),
    path('all/', BlogListView.as_view(), name='blog_list'),
    path('more/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, email_verification, UserListView, UserBanView, UserProfileView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registr/', RegisterView.as_view(), name='register'),
    path('confirm/<str:token>/', email_verification, name='email_verification'),
    path('all/', UserListView.as_view(), name='list_users'),
    path('ban/<int:pk>', UserBanView.as_view(), name='ban_user'),
    path('profile/<int:pk>', UserProfileView.as_view(), name='profile_user'),
]

client/models.py
from django.db import models

from users.models import User

NULLABLE = {
    'blank': True,
    'null': True,
}


class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name="email")
    full_name = models.CharField(max_length=70, verbose_name="full name", **NULLABLE)
    comment = models.CharField(max_length=300, verbose_name="comment", **NULLABLE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="owner")

    def __str__(self):
        return f"{self.email} {self.full_name}"


class Message(models.Model):
    topic = models.CharField(max_length=100, verbose_name="topic")
    message = models.TextField(verbose_name='message')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="owner")

    def __str__(self):
        return f"{self.topic}"


class Mail(models.Model):
    PERIODICITY_CHOICES = [
        ('day', 'Каждый день'),
        ('week', 'Каждую неделю'),
        ('month', 'Каждый месяц'),
    ]

    STATUS_CHOICES = [
        ('created', 'Создана'),
        ('started', 'Запущена'),
        ('failed', 'Ошибка'),
        ('completed', 'Завершена'),
    ]

    time_for_sending = models.DateTimeField(verbose_name="first mailing date")
    periodicity = models.CharField(max_length=20, choices=PERIODICITY_CHOICES, default='week',
                                   verbose_name="periodicity")
    recipients = models.ManyToManyField(Client, related_name='mails', verbose_name="recipients")
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name="message")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='created', verbose_name="status")
    is_active = models.BooleanField(default=True, verbose_name="is active")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='mails', verbose_name="owner")

    def __str__(self):
        return f"{self.pk}"


class Attempt(models.Model):
    last_modified_date = models.DateTimeField(auto_now=True, verbose_name="last modified date")
    mail_response = models.TextField(verbose_name="mail response", **NULLABLE)
    mail = models.ForeignKey(Mail, on_delete=models.CASCADE, related_name='attempt', verbose_name='mail')

    def __str__(self):
        return f"{self.pk}"

users/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True,
            "null": True}


class CustomUserManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')
    phone = models.CharField(max_length=35, verbose_name="phone number", **NULLABLE)
    token = models.CharField(max_length=100, verbose_name='token', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserBanForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('is_active',)


class UserProfileForm(forms.ModelForm):
    new_password = forms.CharField(
        label='New Password',
        required=False,
        widget=forms.PasswordInput(attrs={'placeholder': 'Enter new password'}),
    )
    confirm_password = forms.CharField(
        label='Confirm Password',
        required=False,
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirm new password'})
    )

    class Meta:
        model = User
        fields = ['email', 'phone']
        widgets = {
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'phone': forms.TextInput(attrs={'placeholder': 'Phone number'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        confirm_password = cleaned_data.get('confirm_password')

        if new_password and new_password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")

        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)

        new_password = self.cleaned_data.get('new_password')
        if new_password:
            user.set_password(new_password)

        if commit:
            user.save()

        return user

users/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, UpdateView

from Mailing.settings import EMAIL_HOST_USER
from users.forms import UserRegistrationForm, UserBanForm, UserProfileForm
from users.models import User

import secrets


class RegisterView(CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()

        url = f'http://{self.request.get_host()}/users/confirm/{token}/'

        send_mail(
            subject="Подтверждение почты",
            message=f"ссылка для подтверждения почты:{url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )

        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class UserListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = User
    context_object_name = 'users'
    login_url = reverse_lazy('users:login')

    def test_func(self):
        user = self.request.user
        return user.is_superuser or user.groups.filter(name='Managers').exists()

    def get_queryset(self):
        return User.objects.annotate(mail_count=Count('mails')).filter(
            is_superuser=False,
            groups__isnull=True
        )


class UserBanView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = User
    form_class = UserBanForm
    success_url = reverse_lazy('users:list_users')

    def test_func(self):
        user = self.request.user
        return user.is_superuser or user.groups.filter(name='Managers').exists()


class UserProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/user_profile.html'

    def get_success_url(self):
        return reverse_lazy('users:profile_user', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        response = super().form_valid(form)

        new_password = form.cleaned_data.get('new_password')
        if new_password:
            update_session_auth_hash(self.request, self.object)

        return response

users/templates/users/login.html
{% extends 'client/base.html' %}

{% block products %}
    <div class="row text-center">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>
                    <a href="{% url 'mail:mail_list' %}" class="btn btn-secondary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'client/base.html' %}

{% block products %}
    <div class="row text-center">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Регистрация
                    </button>
                    <a href="{% url 'mail:mail_list' %}" class="btn btn-secondary">Отмена</a>
                </form>
                <h2></h2>
                <h4>На почту будет отправлено письмо с подтверждением</h4>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'client/base.html' %}

{% block products %}
    <div class="row text-center">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Применить
                    </button>
                    <a href="{% url 'users:list_users' %}" class="btn btn-secondary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'client/base.html' %}


{% block products %}
    <div class="row text-center">
        {% for user in users %}
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ user.email }}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>Количество созданных рассылок: {{ user.mail_count }}</li>
                        </ul>
                        <div class="d-flex justify-content-between">
                            <a href="{% url 'users:ban_user' user.pk %}" class="btn btn-info">
                                Заблокировать пользовотеля
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

users/templates/users/user_profile.html
{% extends 'client/base.html' %}

{% block products %}
    <div class="row text-center">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Применить
                    </button>
                    <a href="{% url 'users:list_users' %}" class="btn btn-secondary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}